<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RGTS.Entidades\RGTS.Entidades.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Conexión\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Repositorios\" />
  </ItemGroup>

</Project>
