<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RGTS.AccesoDatos\RGTS.AccesoDatos.csproj" />
    <ProjectReference Include="..\RGTS.Entidades\RGTS.Entidades.csproj" />
  </ItemGroup>

</Project>
